package com.iofairy.test;

import com.iofairy.falcon.time.Interval;
import com.iofairy.falcon.time.SignedInterval;
import com.iofairy.falcon.time.TZ;
import com.iofairy.falcon.util.DateTimeUtils;
import com.iofairy.top.G;
import org.junit.jupiter.api.Test;

import java.time.*;
import java.time.temporal.Temporal;
import java.util.*;

import static org.junit.jupiter.api.Assertions.*;

/**
 * @author GG
 * @version 1.0
 * @date 2021/10/1 8:44
 */
public class IntervalTest {
    @Test
    public void testSignedInterval() {
        ZoneOffset zoneOffset = DateTimeUtils.defaultOffset();
        System.out.println("defaultOffset: " + zoneOffset);
        LocalDateTime fromLocalDateTime = LocalDateTime.of(1903, 6, 15, 10, 56, 43, 987656789);
        Instant fromInstant = fromLocalDateTime.toInstant(zoneOffset);
        OffsetDateTime fromOffsetDateTime = OffsetDateTime.ofInstant(fromInstant, TZ.NEW_YORK);
        ZonedDateTime fromZonedDateTime = ZonedDateTime.ofInstant(fromInstant, TZ.NEW_YORK);
        Date fromDate = Date.from(fromInstant);
        Calendar fromCalendar = DateTimeUtils.calendar(fromInstant);
        // System.out.println(G.dtSimple(fromDate));
        // System.out.println(G.dtSimple(fromCalendar));
        // -----------------------------------------------------------------------------
        LocalDateTime toLocalDateTime = LocalDateTime.of(2020, 8, 10, 3, 33, 10, 987656700);
        Instant toInstant = toLocalDateTime.toInstant(zoneOffset);
        OffsetDateTime toOffsetDateTime = OffsetDateTime.ofInstant(toInstant, TZ.NEW_YORK);
        ZonedDateTime toZonedDateTime = ZonedDateTime.ofInstant(toInstant, TZ.NEW_YORK);
        Date toDate = Date.from(toInstant);
        Calendar toCalendar = DateTimeUtils.calendar(toInstant);
        // System.out.println(G.dtSimple(toDate));
        // System.out.println(G.dtSimple(toCalendar));
        // -----------------------------------------------------------------------------
        SignedInterval signedInterval1 = SignedInterval.between(fromLocalDateTime, toLocalDateTime);
        SignedInterval signedInterval2 = SignedInterval.between(fromLocalDateTime, toInstant);
        SignedInterval signedInterval3 = SignedInterval.between(fromLocalDateTime, toOffsetDateTime);
        SignedInterval signedInterval4 = SignedInterval.between(fromLocalDateTime, toZonedDateTime);
        SignedInterval signedInterval5 = SignedInterval.between(toLocalDateTime, fromLocalDateTime);
        SignedInterval signedInterval6 = SignedInterval.between(toLocalDateTime, fromInstant);
        SignedInterval signedInterval7 = SignedInterval.between(toLocalDateTime, fromOffsetDateTime);
        SignedInterval signedInterval8 = SignedInterval.between(toLocalDateTime, fromZonedDateTime);
        SignedInterval signedInterval9 = SignedInterval.between(fromDate, toDate);
        SignedInterval signedInterval10 = SignedInterval.between(fromCalendar, toCalendar);
        SignedInterval signedInterval11 = SignedInterval.between(toDate, fromDate);
        SignedInterval signedInterval12 = SignedInterval.between(toCalendar, fromCalendar);
        System.out.println(signedInterval1);
        System.out.println(signedInterval2);
        System.out.println(signedInterval3);
        System.out.println(signedInterval4);
        System.out.println(signedInterval5);
        System.out.println(signedInterval6);
        System.out.println(signedInterval7);
        System.out.println(signedInterval8);
        System.out.println(signedInterval9);
        System.out.println(signedInterval10);
        System.out.println(signedInterval11);
        System.out.println(signedInterval12);
        assertEquals("1世纪17年1月25天16时36分26秒999毫秒999微秒911纳秒", signedInterval1.toString());
        assertEquals("1世纪17年1月25天16时36分26秒999毫秒999微秒911纳秒", signedInterval2.toString());
        assertEquals("1世纪17年1月25天16时36分26秒999毫秒999微秒911纳秒", signedInterval3.toString());
        assertEquals("1世纪17年1月25天16时36分26秒999毫秒999微秒911纳秒", signedInterval4.toString());
        assertEquals("-1世纪-17年-1月-24天-16时-36分-26秒-999毫秒-999微秒-911纳秒", signedInterval5.toString());
        assertEquals("-1世纪-17年-1月-24天-16时-36分-26秒-999毫秒-999微秒-911纳秒", signedInterval6.toString());
        assertEquals("-1世纪-17年-1月-24天-16时-36分-26秒-999毫秒-999微秒-911纳秒", signedInterval7.toString());
        assertEquals("-1世纪-17年-1月-24天-16时-36分-26秒-999毫秒-999微秒-911纳秒", signedInterval8.toString());
        assertEquals("1世纪17年1月25天16时36分27秒0毫秒", signedInterval9.toString());
        assertEquals("1世纪17年1月25天16时36分27秒0毫秒", signedInterval10.toString());
        assertEquals("-1世纪-17年-1月-24天-16时-36分-27秒0毫秒", signedInterval11.toString());
        assertEquals("-1世纪-17年-1月-24天-16时-36分-27秒0毫秒", signedInterval12.toString());
        System.out.println("======================================");
        System.out.println(signedInterval1.equals(signedInterval2));
        System.out.println(signedInterval3.equals(signedInterval4));
        System.out.println(signedInterval1.equals(signedInterval5));
        System.out.println(signedInterval7.equals(signedInterval8));
        System.out.println("======================================");
        Temporal temporal1 = signedInterval1.subtractFrom(toInstant);
        Temporal temporal2 = signedInterval1.addTo(fromLocalDateTime);
        Temporal temporal3 = signedInterval6.subtractFrom(fromInstant);
        Temporal temporal4 = signedInterval6.addTo(toLocalDateTime);
        System.out.println(temporal1);
        System.out.println(temporal2);
        System.out.println(temporal3);
        System.out.println(temporal4);
        Date date1 = signedInterval9.addTo(fromDate);
        Date date2 = signedInterval9.subtractFrom(toDate);
        Date date3 = signedInterval11.addTo(toDate);
        Date date4 = signedInterval11.subtractFrom(fromDate);
        Calendar calendar1 = signedInterval10.addTo(fromCalendar);
        Calendar calendar2 = signedInterval10.subtractFrom(toCalendar);
        Calendar calendar3 = signedInterval12.addTo(toCalendar);
        Calendar calendar4 = signedInterval12.subtractFrom(fromCalendar);
        System.out.println(G.dtSimple(date1));
        System.out.println(G.dtSimple(date2));
        System.out.println(G.dtSimple(date3));
        System.out.println(G.dtSimple(date4));
        System.out.println(G.dtSimple(calendar1));
        System.out.println(G.dtSimple(calendar2));
        System.out.println(G.dtSimple(calendar3));
        System.out.println(G.dtSimple(calendar4));
        System.out.println("======================================");
        System.out.println(signedInterval1.toFullString());
        System.out.println(signedInterval5.toFullString());
        System.out.println(signedInterval9.toFullString());
        System.out.println(signedInterval11.toFullString());
    }

    @Test
    public void testSignedInterval1() {
        ZoneOffset zoneOffset = DateTimeUtils.defaultOffset();
        System.out.println("defaultOffset: " + zoneOffset);
        LocalDateTime fromLocalDateTime = LocalDateTime.of(1903, 2, 15, 10, 56, 43, 987656789);
        Instant fromInstant = fromLocalDateTime.toInstant(zoneOffset);
        OffsetDateTime fromOffsetDateTime = OffsetDateTime.ofInstant(fromInstant, TZ.NEW_YORK);
        ZonedDateTime fromZonedDateTime = ZonedDateTime.ofInstant(fromInstant, TZ.NEW_YORK);
        Date fromDate = Date.from(fromInstant);
        Calendar fromCalendar = DateTimeUtils.calendar(fromInstant);
        // System.out.println(G.dtSimple(fromDate));
        // System.out.println(G.dtSimple(fromCalendar));
        // -----------------------------------------------------------------------------
        LocalDateTime toLocalDateTime = LocalDateTime.of(2020, 4, 10, 3, 33, 10, 987656700);
        Instant toInstant = toLocalDateTime.toInstant(zoneOffset);
        OffsetDateTime toOffsetDateTime = OffsetDateTime.ofInstant(toInstant, TZ.NEW_YORK);
        ZonedDateTime toZonedDateTime = ZonedDateTime.ofInstant(toInstant, TZ.NEW_YORK);
        Date toDate = Date.from(toInstant);
        Calendar toCalendar = DateTimeUtils.calendar(toInstant);
        // System.out.println(G.dtSimple(toDate));
        // System.out.println(G.dtSimple(toCalendar));
        // -----------------------------------------------------------------------------
        SignedInterval signedInterval1 = SignedInterval.between(fromLocalDateTime, toLocalDateTime);
        SignedInterval signedInterval2 = SignedInterval.between(fromLocalDateTime, toInstant);
        SignedInterval signedInterval3 = SignedInterval.between(fromLocalDateTime, toOffsetDateTime);
        SignedInterval signedInterval4 = SignedInterval.between(fromLocalDateTime, toZonedDateTime);
        SignedInterval signedInterval5 = SignedInterval.between(toLocalDateTime, fromLocalDateTime);
        SignedInterval signedInterval6 = SignedInterval.between(toLocalDateTime, fromInstant);
        SignedInterval signedInterval7 = SignedInterval.between(toLocalDateTime, fromOffsetDateTime);
        SignedInterval signedInterval8 = SignedInterval.between(toLocalDateTime, fromZonedDateTime);
        SignedInterval signedInterval9 = SignedInterval.between(fromDate, toDate);
        SignedInterval signedInterval10 = SignedInterval.between(fromCalendar, toCalendar);
        SignedInterval signedInterval11 = SignedInterval.between(toDate, fromDate);
        SignedInterval signedInterval12 = SignedInterval.between(toCalendar, fromCalendar);
        System.out.println(signedInterval1);
        System.out.println(signedInterval2);
        System.out.println(signedInterval3);
        System.out.println(signedInterval4);
        System.out.println(signedInterval5);
        System.out.println(signedInterval6);
        System.out.println(signedInterval7);
        System.out.println(signedInterval8);
        System.out.println(signedInterval9);
        System.out.println(signedInterval10);
        System.out.println(signedInterval11);
        System.out.println(signedInterval12);
        assertEquals("1世纪17年1月25天16时36分26秒999毫秒999微秒911纳秒", signedInterval1.toString());
        assertEquals("1世纪17年1月25天16时36分26秒999毫秒999微秒911纳秒", signedInterval2.toString());
        assertEquals("1世纪17年1月25天16时36分26秒999毫秒999微秒911纳秒", signedInterval3.toString());
        assertEquals("1世纪17年1月25天16时36分26秒999毫秒999微秒911纳秒", signedInterval4.toString());
        assertEquals("-1世纪-17年-1月-22天-16时-36分-26秒-999毫秒-999微秒-911纳秒", signedInterval5.toString());
        assertEquals("-1世纪-17年-1月-22天-16时-36分-26秒-999毫秒-999微秒-911纳秒", signedInterval6.toString());
        assertEquals("-1世纪-17年-1月-22天-16时-36分-26秒-999毫秒-999微秒-911纳秒", signedInterval7.toString());
        assertEquals("-1世纪-17年-1月-22天-16时-36分-26秒-999毫秒-999微秒-911纳秒", signedInterval8.toString());
        assertEquals("1世纪17年1月25天16时36分27秒0毫秒", signedInterval9.toString());
        assertEquals("1世纪17年1月25天16时36分27秒0毫秒", signedInterval10.toString());
        assertEquals("-1世纪-17年-1月-22天-16时-36分-27秒0毫秒", signedInterval11.toString());
        assertEquals("-1世纪-17年-1月-22天-16时-36分-27秒0毫秒", signedInterval12.toString());
        System.out.println("======================================");
        System.out.println(signedInterval1.equals(signedInterval2));
        System.out.println(signedInterval3.equals(signedInterval4));
        System.out.println(signedInterval1.equals(signedInterval5));
        System.out.println(signedInterval7.equals(signedInterval8));
        System.out.println("======================================");
        Temporal temporal1 = signedInterval1.subtractFrom(toInstant);
        Temporal temporal2 = signedInterval1.addTo(fromLocalDateTime);
        Temporal temporal3 = signedInterval6.subtractFrom(fromInstant);
        Temporal temporal4 = signedInterval6.addTo(toLocalDateTime);
        System.out.println(temporal1);
        System.out.println(temporal2);
        System.out.println(temporal3);
        System.out.println(temporal4);
        Date date1 = signedInterval9.addTo(fromDate);
        Date date2 = signedInterval9.subtractFrom(toDate);
        Date date3 = signedInterval11.addTo(toDate);
        Date date4 = signedInterval11.subtractFrom(fromDate);
        Calendar calendar1 = signedInterval10.addTo(fromCalendar);
        Calendar calendar2 = signedInterval10.subtractFrom(toCalendar);
        Calendar calendar3 = signedInterval12.addTo(toCalendar);
        Calendar calendar4 = signedInterval12.subtractFrom(fromCalendar);
        System.out.println(G.dtSimple(date1));
        System.out.println(G.dtSimple(date2));
        System.out.println(G.dtSimple(date3));
        System.out.println(G.dtSimple(date4));
        System.out.println(G.dtSimple(calendar1));
        System.out.println(G.dtSimple(calendar2));
        System.out.println(G.dtSimple(calendar3));
        System.out.println(G.dtSimple(calendar4));
        System.out.println("======================================");
        System.out.println(signedInterval1.toFullString());
        System.out.println(signedInterval5.toFullString());
        System.out.println(signedInterval9.toFullString());
        System.out.println(signedInterval11.toFullString());
    }

    @Test
    public void testInterval() {
        ZoneOffset zoneOffset = DateTimeUtils.defaultOffset();
        System.out.println("defaultOffset: " + zoneOffset);
        LocalDateTime fromLocalDateTime = LocalDateTime.of(1903, 6, 15, 10, 56, 43, 987656789);
        Instant fromInstant = fromLocalDateTime.toInstant(zoneOffset);
        OffsetDateTime fromOffsetDateTime = OffsetDateTime.ofInstant(fromInstant, TZ.NEW_YORK);
        ZonedDateTime fromZonedDateTime = ZonedDateTime.ofInstant(fromInstant, TZ.NEW_YORK);
        Date fromDate = Date.from(fromInstant);
        Calendar fromCalendar = DateTimeUtils.calendar(fromInstant);
        // System.out.println(G.dtSimple(fromDate));
        // System.out.println(G.dtSimple(fromCalendar));
        // -----------------------------------------------------------------------------
        LocalDateTime toLocalDateTime = LocalDateTime.of(2020, 8, 10, 3, 33, 10, 987656700);
        Instant toInstant = toLocalDateTime.toInstant(zoneOffset);
        OffsetDateTime toOffsetDateTime = OffsetDateTime.ofInstant(toInstant, TZ.NEW_YORK);
        ZonedDateTime toZonedDateTime = ZonedDateTime.ofInstant(toInstant, TZ.NEW_YORK);
        Date toDate = Date.from(toInstant);
        Calendar toCalendar = DateTimeUtils.calendar(toInstant);
        // System.out.println(G.dtSimple(toDate));
        // System.out.println(G.dtSimple(toCalendar));
        // -----------------------------------------------------------------------------
        Interval interval1 = Interval.between(fromLocalDateTime, toLocalDateTime);
        Interval interval2 = Interval.between(fromLocalDateTime, toInstant);
        Interval interval3 = Interval.between(fromLocalDateTime, toOffsetDateTime);
        Interval interval4 = Interval.between(fromLocalDateTime, toZonedDateTime);
        Interval interval5 = Interval.between(toLocalDateTime, fromLocalDateTime);
        Interval interval6 = Interval.between(toLocalDateTime, fromInstant);
        Interval interval7 = Interval.between(toLocalDateTime, fromOffsetDateTime);
        Interval interval8 = Interval.between(toLocalDateTime, fromZonedDateTime);
        Interval interval9 = Interval.between(fromDate, toDate);
        Interval interval10 = Interval.between(fromCalendar, toCalendar);
        Interval interval11 = Interval.between(toDate, fromDate);
        Interval interval12 = Interval.between(toCalendar, fromCalendar);
        System.out.println(interval1);
        System.out.println(interval2);
        System.out.println(interval3);
        System.out.println(interval4);
        System.out.println(interval5);
        System.out.println(interval6);
        System.out.println(interval7);
        System.out.println(interval8);
        System.out.println(interval9);
        System.out.println(interval10);
        System.out.println(interval11);
        System.out.println(interval12);
        assertEquals("1世纪17年1月25天16时36分26秒999毫秒999微秒911纳秒", interval1.toString());
        assertEquals("1世纪17年1月25天16时36分26秒999毫秒999微秒911纳秒", interval2.toString());
        assertEquals("1世纪17年1月25天16时36分26秒999毫秒999微秒911纳秒", interval3.toString());
        assertEquals("1世纪17年1月25天16时36分26秒999毫秒999微秒911纳秒", interval4.toString());
        assertEquals("1世纪17年1月25天16时36分26秒999毫秒999微秒911纳秒", interval5.toString());
        assertEquals("1世纪17年1月25天16时36分26秒999毫秒999微秒911纳秒", interval6.toString());
        assertEquals("1世纪17年1月25天16时36分26秒999毫秒999微秒911纳秒", interval7.toString());
        assertEquals("1世纪17年1月25天16时36分26秒999毫秒999微秒911纳秒", interval8.toString());
        assertEquals("1世纪17年1月25天16时36分27秒0毫秒", interval9.toString());
        assertEquals("1世纪17年1月25天16时36分27秒0毫秒", interval10.toString());
        assertEquals("1世纪17年1月25天16时36分27秒0毫秒", interval11.toString());
        assertEquals("1世纪17年1月25天16时36分27秒0毫秒", interval12.toString());
        System.out.println("======================================");
        System.out.println(interval1.equals(interval2));
        System.out.println(interval3.equals(interval4));
        System.out.println(interval1.equals(interval5));
        System.out.println(interval7.equals(interval8));
        System.out.println("======================================");
        Temporal temporal1 = interval1.subtractFrom(toInstant);
        Temporal temporal2 = interval1.addTo(fromLocalDateTime);
        Temporal temporal3 = interval6.subtractFrom(fromInstant);
        Temporal temporal4 = interval6.addTo(toLocalDateTime);
        System.out.println(temporal1);
        System.out.println(temporal2);
        System.out.println(temporal3);
        System.out.println(temporal4);
        Date date1 = interval9.addTo(fromDate);
        Date date2 = interval9.subtractFrom(toDate);
        Calendar calendar1 = interval10.addTo(fromCalendar);
        Calendar calendar2 = interval10.subtractFrom(toCalendar);
        System.out.println(G.dtSimple(date1));
        System.out.println(G.dtSimple(date2));
        System.out.println(G.dtSimple(calendar1));
        System.out.println(G.dtSimple(calendar2));
        System.out.println("======================================");
        System.out.println(interval1.toFullString());
        System.out.println(interval5.toFullString());
        System.out.println(interval9.toFullString());
        System.out.println(interval11.toFullString());
    }

    @Test
    public void testInterval1() {
        ZoneOffset zoneOffset = DateTimeUtils.defaultOffset();
        System.out.println("defaultOffset: " + zoneOffset);
        LocalDateTime fromLocalDateTime = LocalDateTime.of(1903, 2, 15, 10, 56, 43, 987656789);
        Instant fromInstant = fromLocalDateTime.toInstant(zoneOffset);
        OffsetDateTime fromOffsetDateTime = OffsetDateTime.ofInstant(fromInstant, TZ.NEW_YORK);
        ZonedDateTime fromZonedDateTime = ZonedDateTime.ofInstant(fromInstant, TZ.NEW_YORK);
        Date fromDate = Date.from(fromInstant);
        Calendar fromCalendar = DateTimeUtils.calendar(fromInstant);
        // System.out.println(G.dtSimple(fromDate));
        // System.out.println(G.dtSimple(fromCalendar));
        // -----------------------------------------------------------------------------
        LocalDateTime toLocalDateTime = LocalDateTime.of(2020, 4, 10, 3, 33, 10, 987656700);
        Instant toInstant = toLocalDateTime.toInstant(zoneOffset);
        OffsetDateTime toOffsetDateTime = OffsetDateTime.ofInstant(toInstant, TZ.NEW_YORK);
        ZonedDateTime toZonedDateTime = ZonedDateTime.ofInstant(toInstant, TZ.NEW_YORK);
        Date toDate = Date.from(toInstant);
        Calendar toCalendar = DateTimeUtils.calendar(toInstant);
        // System.out.println(G.dtSimple(toDate));
        // System.out.println(G.dtSimple(toCalendar));
        // -----------------------------------------------------------------------------
        Interval interval1 = Interval.between(fromLocalDateTime, toLocalDateTime);
        Interval interval2 = Interval.between(fromLocalDateTime, toInstant);
        Interval interval3 = Interval.between(fromLocalDateTime, toOffsetDateTime);
        Interval interval4 = Interval.between(fromLocalDateTime, toZonedDateTime);
        Interval interval5 = Interval.between(toLocalDateTime, fromLocalDateTime);
        Interval interval6 = Interval.between(toLocalDateTime, fromInstant);
        Interval interval7 = Interval.between(toLocalDateTime, fromOffsetDateTime);
        Interval interval8 = Interval.between(toLocalDateTime, fromZonedDateTime);
        Interval interval9 = Interval.between(fromDate, toDate);
        Interval interval10 = Interval.between(fromCalendar, toCalendar);
        Interval interval11 = Interval.between(toDate, fromDate);
        Interval interval12 = Interval.between(toCalendar, fromCalendar);
        System.out.println(interval1);
        System.out.println(interval2);
        System.out.println(interval3);
        System.out.println(interval4);
        System.out.println(interval5);
        System.out.println(interval6);
        System.out.println(interval7);
        System.out.println(interval8);
        System.out.println(interval9);
        System.out.println(interval10);
        System.out.println(interval11);
        System.out.println(interval12);
        assertEquals("1世纪17年1月25天16时36分26秒999毫秒999微秒911纳秒", interval1.toString());
        assertEquals("1世纪17年1月25天16时36分26秒999毫秒999微秒911纳秒", interval2.toString());
        assertEquals("1世纪17年1月25天16时36分26秒999毫秒999微秒911纳秒", interval3.toString());
        assertEquals("1世纪17年1月25天16时36分26秒999毫秒999微秒911纳秒", interval4.toString());
        assertEquals("1世纪17年1月25天16时36分26秒999毫秒999微秒911纳秒", interval5.toString());
        assertEquals("1世纪17年1月25天16时36分26秒999毫秒999微秒911纳秒", interval6.toString());
        assertEquals("1世纪17年1月25天16时36分26秒999毫秒999微秒911纳秒", interval7.toString());
        assertEquals("1世纪17年1月25天16时36分26秒999毫秒999微秒911纳秒", interval8.toString());
        assertEquals("1世纪17年1月25天16时36分27秒0毫秒", interval9.toString());
        assertEquals("1世纪17年1月25天16时36分27秒0毫秒", interval10.toString());
        assertEquals("1世纪17年1月25天16时36分27秒0毫秒", interval11.toString());
        assertEquals("1世纪17年1月25天16时36分27秒0毫秒", interval12.toString());
        System.out.println("======================================");
        System.out.println(interval1.equals(interval2));
        System.out.println(interval3.equals(interval4));
        System.out.println(interval1.equals(interval5));
        System.out.println(interval7.equals(interval8));
        System.out.println("======================================");
        Temporal temporal1 = interval1.subtractFrom(toInstant);
        Temporal temporal2 = interval1.addTo(fromLocalDateTime);
        Temporal temporal3 = interval6.subtractFrom(fromInstant);
        Temporal temporal4 = interval6.addTo(toLocalDateTime);
        System.out.println(temporal1);
        System.out.println(temporal2);
        System.out.println(temporal3);
        System.out.println(temporal4);
        Date date1 = interval9.addTo(fromDate);
        Date date2 = interval9.subtractFrom(toDate);
        Calendar calendar1 = interval10.addTo(fromCalendar);
        Calendar calendar2 = interval10.subtractFrom(toCalendar);
        System.out.println(G.dtSimple(date1));
        System.out.println(G.dtSimple(date2));
        System.out.println(G.dtSimple(calendar1));
        System.out.println(G.dtSimple(calendar2));
        System.out.println("======================================");
        System.out.println(interval1.toFullString());
        System.out.println(interval5.toFullString());
        System.out.println(interval9.toFullString());
        System.out.println(interval11.toFullString());
    }

}
