package com.iofairy.test;

import com.iofairy.falcon.fs.FilePath;
import com.iofairy.falcon.fs.PathInfo;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

/**
 * @author GG
 * @version 1.0
 * @date 2022/9/11 9:40
 */
public class PathInfoTest {


    @Test
    public void testPathInfo() {
        PathInfo info01 = FilePath.info("");
        PathInfo info02 = FilePath.info("/");
        PathInfo info03 = FilePath.info("\\");
        PathInfo info04 = FilePath.info(".");
        PathInfo info05 = FilePath.info("/\\");
        PathInfo info06 = FilePath.info("///a");
        PathInfo info07 = FilePath.info("///a/b/");
        PathInfo info08 = FilePath.info("./a/b\\c\\");
        PathInfo info09 = FilePath.info(".///a\\b//\\c");
        PathInfo info10 = FilePath.info(".///a\\b//\\c/");
        PathInfo info11 = FilePath.info(".///a/111.abc.txt");
        PathInfo info12 = FilePath.info(".///a/111.abc.tx\\t");
        PathInfo info13 = FilePath.info(".///a/111.abc.tx/t");
        PathInfo info14 = FilePath.info(".///a/111.abc.txt\\");
        PathInfo info15 = FilePath.info(".///a\\b//\\c/.");
        PathInfo info16 = FilePath.info(".///a\\b//\\c/..");
        PathInfo info17 = FilePath.info(".///a\\b//\\c/..\\");
        PathInfo info18 = FilePath.info(".///a\\b//\\c/../");
        PathInfo info19 = FilePath.info("..");
        PathInfo info20 = FilePath.info("..\\");
        PathInfo info21 = FilePath.info("../");
        PathInfo info22 = FilePath.info("......");
        PathInfo info23 = FilePath.info(".... ..");
        PathInfo info24 = FilePath.info("./abc.");
        PathInfo info25 = FilePath.info("./abc...");
        PathInfo info26 = FilePath.info("./abc.tar.gz");
        PathInfo info27 = FilePath.info("C:");
        PathInfo info28 = FilePath.info("d:/");
        PathInfo info29 = FilePath.info("d:\\");
        PathInfo info30 = FilePath.info("d:/a");
        PathInfo info31 = FilePath.info("d:\\a");
        PathInfo info32 = FilePath.info("d:a");
        PathInfo info33 = FilePath.info("d:a/");
        PathInfo info34 = FilePath.info("d:a\\");
        PathInfo info35 = FilePath.info("ad:");
        PathInfo info36 = FilePath.info("ad:/");
        PathInfo info37 = FilePath.info("ad:\\");
        PathInfo info38 = FilePath.info("/d:");
        PathInfo info39 = FilePath.info("/d:/");
        PathInfo info40 = FilePath.info("/d:\\");
        PathInfo info41 = FilePath.info("/d:/a");
        PathInfo info42 = FilePath.info("\\d:");
        PathInfo info43 = FilePath.info("\\d:/");
        PathInfo info44 = FilePath.info("\\d:\\");
        PathInfo info45 = FilePath.info("\\d:/a");

        // System.out.println("info01: " + info01);
        // System.out.println("info02: " + info02);
        // System.out.println("info03: " + info03);
        // System.out.println("info04: " + info04);
        // System.out.println("info05: " + info05);
        // System.out.println("info06: " + info06);
        // System.out.println("info07: " + info07);
        // System.out.println("info08: " + info08);
        // System.out.println("info09: " + info09);
        // System.out.println("info10: " + info10);
        // System.out.println("info11: " + info11);
        // System.out.println("info12: " + info12);
        // System.out.println("info13: " + info13);
        // System.out.println("info14: " + info14);
        // System.out.println("info15: " + info15);
        // System.out.println("info16: " + info16);
        // System.out.println("info17: " + info17);
        // System.out.println("info18: " + info18);
        // System.out.println("info19: " + info19);
        // System.out.println("info20: " + info20);
        // System.out.println("info21: " + info21);
        // System.out.println("info22: " + info22);
        // System.out.println("info23: " + info23);
        // System.out.println("info24: " + info24);
        // System.out.println("info25: " + info25);
        // System.out.println("info26: " + info26);
        // System.out.println("info27: " + info27);
        // System.out.println("info28: " + info28);
        // System.out.println("info29: " + info29);
        // System.out.println("info30: " + info30);
        // System.out.println("info31: " + info31);
        // System.out.println("info32: " + info32);
        // System.out.println("info33: " + info33);
        // System.out.println("info34: " + info34);
        // System.out.println("info35: " + info35);
        // System.out.println("info36: " + info36);
        // System.out.println("info37: " + info37);
        // System.out.println("info38: " + info38);
        // System.out.println("info39: " + info39);
        // System.out.println("info40: " + info40);
        // System.out.println("info41: " + info41);
        // System.out.println("info42: " + info42);
        // System.out.println("info43: " + info43);
        // System.out.println("info44: " + info44);
        // System.out.println("info45: " + info45);

        assertNull(info01);
        assertEquals(info02.toString(), "PathInfo{hasRoot=true, root='/', fullPath='/', parentPath=null, fileName=FileName{name=null, exts=null, nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[], separator='/', separatorType=SLASH}");
        assertEquals(info03.toString(), "PathInfo{hasRoot=false, root=null, fullPath='\\', parentPath=null, fileName=FileName{name='\\', exts=[], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"\\\"], separator='/', separatorType=SLASH}");
        assertEquals(info04.toString(), "PathInfo{hasRoot=false, root=null, fullPath='.', parentPath=null, fileName=FileName{name='.', exts=[], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\".\"], separator='/', separatorType=SLASH}");
        assertEquals(info05.toString(), "PathInfo{hasRoot=true, root='/', fullPath='/\\', parentPath='/', fileName=FileName{name='\\', exts=[], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"\", \"\\\"], separator='/', separatorType=SLASH}");
        assertEquals(info06.toString(), "PathInfo{hasRoot=true, root='/', fullPath='/a', parentPath='/', fileName=FileName{name='a', exts=[\"a\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"\", \"a\"], separator='/', separatorType=SLASH}");
        assertEquals(info07.toString(), "PathInfo{hasRoot=true, root='/', fullPath='/a/b', parentPath='/a', fileName=FileName{name='b', exts=[\"b\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"\", \"a\", \"b\"], separator='/', separatorType=SLASH}");
        assertEquals(info08.toString(), "PathInfo{hasRoot=false, root=null, fullPath='./a/b\\c\\', parentPath='./a', fileName=FileName{name='b\\c\\', exts=[], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\".\", \"a\", \"b\\c\\\"], separator='/', separatorType=SLASH}");
        assertEquals(info09.toString(), "PathInfo{hasRoot=false, root=null, fullPath='./a\\b/\\c', parentPath='./a\\b', fileName=FileName{name='\\c', exts=[\"\\c\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\".\", \"a\\b\", \"\\c\"], separator='/', separatorType=SLASH}");
        assertEquals(info10.toString(), "PathInfo{hasRoot=false, root=null, fullPath='./a\\b/\\c', parentPath='./a\\b', fileName=FileName{name='\\c', exts=[\"\\c\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\".\", \"a\\b\", \"\\c\"], separator='/', separatorType=SLASH}");
        assertEquals(info11.toString(), "PathInfo{hasRoot=false, root=null, fullPath='./a/111.abc.txt', parentPath='./a', fileName=FileName{name='111.abc.txt', exts=[\"111\", \"abc\", \"txt\"], nameNoExt='111.abc', nameNoExt1='111', nameNoExt2=null, ext='.txt', ext1='.abc.txt', ext2=null, extNoDot='txt', extNoDot1='abc.txt', extNoDot2=null}, paths=[\".\", \"a\", \"111.abc.txt\"], separator='/', separatorType=SLASH}");
        assertEquals(info12.toString(), "PathInfo{hasRoot=false, root=null, fullPath='./a/111.abc.tx\\t', parentPath='./a', fileName=FileName{name='111.abc.tx\\t', exts=[\"111\", \"abc\", \"tx\\t\"], nameNoExt='111.abc', nameNoExt1='111', nameNoExt2=null, ext='.tx\\t', ext1='.abc.tx\\t', ext2=null, extNoDot='tx\\t', extNoDot1='abc.tx\\t', extNoDot2=null}, paths=[\".\", \"a\", \"111.abc.tx\\t\"], separator='/', separatorType=SLASH}");
        assertEquals(info13.toString(), "PathInfo{hasRoot=false, root=null, fullPath='./a/111.abc.tx/t', parentPath='./a/111.abc.tx', fileName=FileName{name='t', exts=[\"t\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\".\", \"a\", \"111.abc.tx\", \"t\"], separator='/', separatorType=SLASH}");
        assertEquals(info14.toString(), "PathInfo{hasRoot=false, root=null, fullPath='./a/111.abc.txt\\', parentPath='./a', fileName=FileName{name='111.abc.txt\\', exts=[], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\".\", \"a\", \"111.abc.txt\\\"], separator='/', separatorType=SLASH}");
        assertEquals(info15.toString(), "PathInfo{hasRoot=false, root=null, fullPath='./a\\b/\\c', parentPath='./a\\b', fileName=FileName{name='\\c', exts=[\"\\c\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\".\", \"a\\b\", \"\\c\"], separator='/', separatorType=SLASH}");
        assertEquals(info16.toString(), "PathInfo{hasRoot=false, root=null, fullPath='./a\\b/\\c/..', parentPath='./a\\b/\\c', fileName=FileName{name='..', exts=[], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\".\", \"a\\b\", \"\\c\", \"..\"], separator='/', separatorType=SLASH}");
        assertEquals(info17.toString(), "PathInfo{hasRoot=false, root=null, fullPath='./a\\b/\\c/..\\', parentPath='./a\\b/\\c', fileName=FileName{name='..\\', exts=[], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\".\", \"a\\b\", \"\\c\", \"..\\\"], separator='/', separatorType=SLASH}");
        assertEquals(info18.toString(), "PathInfo{hasRoot=false, root=null, fullPath='./a\\b/\\c/..', parentPath='./a\\b/\\c', fileName=FileName{name='..', exts=[], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\".\", \"a\\b\", \"\\c\", \"..\"], separator='/', separatorType=SLASH}");
        assertEquals(info19.toString(), "PathInfo{hasRoot=false, root=null, fullPath='..', parentPath=null, fileName=FileName{name='..', exts=[], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"..\"], separator='/', separatorType=SLASH}");
        assertEquals(info20.toString(), "PathInfo{hasRoot=false, root=null, fullPath='..\\', parentPath=null, fileName=FileName{name='..\\', exts=[], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"..\\\"], separator='/', separatorType=SLASH}");
        assertEquals(info21.toString(), "PathInfo{hasRoot=false, root=null, fullPath='..', parentPath=null, fileName=FileName{name='..', exts=[], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"..\"], separator='/', separatorType=SLASH}");
        assertEquals(info22.toString(), "PathInfo{hasRoot=false, root=null, fullPath='......', parentPath=null, fileName=FileName{name='......', exts=[], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"......\"], separator='/', separatorType=SLASH}");
        assertEquals(info23.toString(), "PathInfo{hasRoot=false, root=null, fullPath='.... ..', parentPath=null, fileName=FileName{name='.... ..', exts=[\"\", \"\", \"\", \"\", \" \", \"\", \"\"], nameNoExt='.... .', nameNoExt1='.... ', nameNoExt2='...', ext='.', ext1='..', ext2='. ..', extNoDot='', extNoDot1='.', extNoDot2=' ..'}, paths=[\".... ..\"], separator='/', separatorType=SLASH}");
        assertEquals(info24.toString(), "PathInfo{hasRoot=false, root=null, fullPath='./abc.', parentPath='.', fileName=FileName{name='abc.', exts=[\"abc\", \"\"], nameNoExt='abc', nameNoExt1=null, nameNoExt2=null, ext='.', ext1=null, ext2=null, extNoDot='', extNoDot1=null, extNoDot2=null}, paths=[\".\", \"abc.\"], separator='/', separatorType=SLASH}");
        assertEquals(info25.toString(), "PathInfo{hasRoot=false, root=null, fullPath='./abc...', parentPath='.', fileName=FileName{name='abc...', exts=[\"abc\", \"\", \"\", \"\"], nameNoExt='abc..', nameNoExt1='abc.', nameNoExt2='abc', ext='.', ext1='..', ext2='...', extNoDot='', extNoDot1='.', extNoDot2='..'}, paths=[\".\", \"abc...\"], separator='/', separatorType=SLASH}");
        assertEquals(info26.toString(), "PathInfo{hasRoot=false, root=null, fullPath='./abc.tar.gz', parentPath='.', fileName=FileName{name='abc.tar.gz', exts=[\"abc\", \"tar\", \"gz\"], nameNoExt='abc.tar', nameNoExt1='abc', nameNoExt2=null, ext='.gz', ext1='.tar.gz', ext2=null, extNoDot='gz', extNoDot1='tar.gz', extNoDot2=null}, paths=[\".\", \"abc.tar.gz\"], separator='/', separatorType=SLASH}");
        assertEquals(info27.toString(), "PathInfo{hasRoot=false, root=null, fullPath='C:', parentPath=null, fileName=FileName{name='C:', exts=[\"C:\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"C:\"], separator='/', separatorType=SLASH}");
        assertEquals(info28.toString(), "PathInfo{hasRoot=false, root=null, fullPath='d:', parentPath=null, fileName=FileName{name='d:', exts=[\"d:\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"d:\"], separator='/', separatorType=SLASH}");
        assertEquals(info29.toString(), "PathInfo{hasRoot=false, root=null, fullPath='d:\\', parentPath=null, fileName=FileName{name='d:\\', exts=[], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"d:\\\"], separator='/', separatorType=SLASH}");
        assertEquals(info30.toString(), "PathInfo{hasRoot=false, root=null, fullPath='d:/a', parentPath='d:', fileName=FileName{name='a', exts=[\"a\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"d:\", \"a\"], separator='/', separatorType=SLASH}");
        assertEquals(info31.toString(), "PathInfo{hasRoot=false, root=null, fullPath='d:\\a', parentPath=null, fileName=FileName{name='d:\\a', exts=[\"d:\\a\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"d:\\a\"], separator='/', separatorType=SLASH}");
        assertEquals(info32.toString(), "PathInfo{hasRoot=false, root=null, fullPath='d:a', parentPath=null, fileName=FileName{name='d:a', exts=[\"d:a\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"d:a\"], separator='/', separatorType=SLASH}");
        assertEquals(info33.toString(), "PathInfo{hasRoot=false, root=null, fullPath='d:a', parentPath=null, fileName=FileName{name='d:a', exts=[\"d:a\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"d:a\"], separator='/', separatorType=SLASH}");
        assertEquals(info34.toString(), "PathInfo{hasRoot=false, root=null, fullPath='d:a\\', parentPath=null, fileName=FileName{name='d:a\\', exts=[], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"d:a\\\"], separator='/', separatorType=SLASH}");
        assertEquals(info35.toString(), "PathInfo{hasRoot=false, root=null, fullPath='ad:', parentPath=null, fileName=FileName{name='ad:', exts=[\"ad:\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"ad:\"], separator='/', separatorType=SLASH}");
        assertEquals(info36.toString(), "PathInfo{hasRoot=false, root=null, fullPath='ad:', parentPath=null, fileName=FileName{name='ad:', exts=[\"ad:\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"ad:\"], separator='/', separatorType=SLASH}");
        assertEquals(info37.toString(), "PathInfo{hasRoot=false, root=null, fullPath='ad:\\', parentPath=null, fileName=FileName{name='ad:\\', exts=[], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"ad:\\\"], separator='/', separatorType=SLASH}");
        assertEquals(info38.toString(), "PathInfo{hasRoot=true, root='/', fullPath='/d:', parentPath='/', fileName=FileName{name='d:', exts=[\"d:\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"\", \"d:\"], separator='/', separatorType=SLASH}");
        assertEquals(info39.toString(), "PathInfo{hasRoot=true, root='/', fullPath='/d:', parentPath='/', fileName=FileName{name='d:', exts=[\"d:\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"\", \"d:\"], separator='/', separatorType=SLASH}");
        assertEquals(info40.toString(), "PathInfo{hasRoot=true, root='/', fullPath='/d:\\', parentPath='/', fileName=FileName{name='d:\\', exts=[], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"\", \"d:\\\"], separator='/', separatorType=SLASH}");
        assertEquals(info41.toString(), "PathInfo{hasRoot=true, root='/', fullPath='/d:/a', parentPath='/d:', fileName=FileName{name='a', exts=[\"a\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"\", \"d:\", \"a\"], separator='/', separatorType=SLASH}");
        assertEquals(info42.toString(), "PathInfo{hasRoot=false, root=null, fullPath='\\d:', parentPath=null, fileName=FileName{name='\\d:', exts=[\"\\d:\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"\\d:\"], separator='/', separatorType=SLASH}");
        assertEquals(info43.toString(), "PathInfo{hasRoot=false, root=null, fullPath='\\d:', parentPath=null, fileName=FileName{name='\\d:', exts=[\"\\d:\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"\\d:\"], separator='/', separatorType=SLASH}");
        assertEquals(info44.toString(), "PathInfo{hasRoot=false, root=null, fullPath='\\d:\\', parentPath=null, fileName=FileName{name='\\d:\\', exts=[], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"\\d:\\\"], separator='/', separatorType=SLASH}");
        assertEquals(info45.toString(), "PathInfo{hasRoot=false, root=null, fullPath='\\d:/a', parentPath='\\d:', fileName=FileName{name='a', exts=[\"a\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"\\d:\", \"a\"], separator='/', separatorType=SLASH}");


    }

    @Test
    public void testPathInfoWin() {
        PathInfo info01 = FilePath.infoWin("");
        PathInfo info02 = FilePath.infoWin("/");
        PathInfo info03 = FilePath.infoWin("\\");
        PathInfo info04 = FilePath.infoWin(".");
        PathInfo info05 = FilePath.infoWin("/\\");
        PathInfo info06 = FilePath.infoWin("///a");
        PathInfo info07 = FilePath.infoWin("///a/b/");
        PathInfo info08 = FilePath.infoWin("./a/b\\c\\");
        PathInfo info09 = FilePath.infoWin(".///a\\b//\\c");
        PathInfo info10 = FilePath.infoWin(".///a\\b//\\c/");
        PathInfo info11 = FilePath.infoWin(".///a/111.abc.txt");
        PathInfo info12 = FilePath.infoWin(".///a/111.abc.tx\\t");
        PathInfo info13 = FilePath.infoWin(".///a/111.abc.tx/t");
        PathInfo info14 = FilePath.infoWin(".///a/111.abc.txt/");
        PathInfo info15 = FilePath.infoWin(".///a\\b//\\c/.");
        PathInfo info16 = FilePath.infoWin(".///a\\b//\\c/..");
        PathInfo info17 = FilePath.infoWin(".///a\\b//\\c/..\\");
        PathInfo info18 = FilePath.infoWin(".///a\\b//\\c/../");
        PathInfo info19 = FilePath.infoWin("..");
        PathInfo info20 = FilePath.infoWin("..\\");
        PathInfo info21 = FilePath.infoWin("../");
        PathInfo info22 = FilePath.infoWin("......");
        PathInfo info23 = FilePath.infoWin(".... ..");
        PathInfo info24 = FilePath.infoWin("./abc.");
        PathInfo info25 = FilePath.infoWin("./abc...");
        PathInfo info26 = FilePath.infoWin("./abc.tar.gz");
        PathInfo info27 = FilePath.infoWin("C:");
        PathInfo info28 = FilePath.infoWin("d:/");
        PathInfo info29 = FilePath.infoWin("d:\\");
        PathInfo info30 = FilePath.infoWin("d:/a");
        PathInfo info31 = FilePath.infoWin("d:\\a");
        PathInfo info32 = FilePath.infoWin("d:a");
        PathInfo info33 = FilePath.infoWin("d:a/");
        PathInfo info34 = FilePath.infoWin("d:a\\");
        PathInfo info35 = FilePath.infoWin("ad:");
        PathInfo info36 = FilePath.infoWin("ad:/");
        PathInfo info37 = FilePath.infoWin("ad:\\");
        PathInfo info38 = FilePath.infoWin("/d:");
        PathInfo info39 = FilePath.infoWin("/d:/");
        PathInfo info40 = FilePath.infoWin("/d:\\");
        PathInfo info41 = FilePath.infoWin("/d:/a");
        PathInfo info42 = FilePath.infoWin("\\d:");
        PathInfo info43 = FilePath.infoWin("\\d:/");
        PathInfo info44 = FilePath.infoWin("\\d:\\");
        PathInfo info45 = FilePath.infoWin("\\d:/a");

        // System.out.println("info01: " + info01);
        // System.out.println("info02: " + info02);
        // System.out.println("info03: " + info03);
        // System.out.println("info04: " + info04);
        // System.out.println("info05: " + info05);
        // System.out.println("info06: " + info06);
        // System.out.println("info07: " + info07);
        // System.out.println("info08: " + info08);
        // System.out.println("info09: " + info09);
        // System.out.println("info10: " + info10);
        // System.out.println("info11: " + info11);
        // System.out.println("info12: " + info12);
        // System.out.println("info13: " + info13);
        // System.out.println("info14: " + info14);
        // System.out.println("info15: " + info15);
        // System.out.println("info16: " + info16);
        // System.out.println("info17: " + info17);
        // System.out.println("info18: " + info18);
        // System.out.println("info19: " + info19);
        // System.out.println("info20: " + info20);
        // System.out.println("info21: " + info21);
        // System.out.println("info22: " + info22);
        // System.out.println("info23: " + info23);
        // System.out.println("info24: " + info24);
        // System.out.println("info25: " + info25);
        // System.out.println("info26: " + info26);
        // System.out.println("info27: " + info27);
        // System.out.println("info28: " + info28);
        // System.out.println("info29: " + info29);
        // System.out.println("info30: " + info30);
        // System.out.println("info31: " + info31);
        // System.out.println("info32: " + info32);
        // System.out.println("info33: " + info33);
        // System.out.println("info34: " + info34);
        // System.out.println("info35: " + info35);
        // System.out.println("info36: " + info36);
        // System.out.println("info37: " + info37);
        // System.out.println("info38: " + info38);
        // System.out.println("info39: " + info39);
        // System.out.println("info40: " + info40);
        // System.out.println("info41: " + info41);
        // System.out.println("info42: " + info42);
        // System.out.println("info43: " + info43);
        // System.out.println("info44: " + info44);
        // System.out.println("info45: " + info45);

        assertNull(info01);
        assertEquals(info02.toString(), "PathInfo{hasRoot=true, root='\\', fullPath='\\', parentPath=null, fileName=FileName{name=null, exts=null, nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[], separator='\\', separatorType=BACKSLASH}");
        assertEquals(info03.toString(), "PathInfo{hasRoot=true, root='\\', fullPath='\\', parentPath=null, fileName=FileName{name=null, exts=null, nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[], separator='\\', separatorType=BACKSLASH}");
        assertEquals(info04.toString(), "PathInfo{hasRoot=false, root=null, fullPath='.', parentPath=null, fileName=FileName{name='.', exts=[], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\".\"], separator='\\', separatorType=BACKSLASH}");
        assertEquals(info05.toString(), "PathInfo{hasRoot=true, root='\\', fullPath='\\', parentPath=null, fileName=FileName{name=null, exts=null, nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[], separator='\\', separatorType=BACKSLASH}");
        assertEquals(info06.toString(), "PathInfo{hasRoot=true, root='\\', fullPath='\\a', parentPath='\\', fileName=FileName{name='a', exts=[\"a\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"\", \"a\"], separator='\\', separatorType=BACKSLASH}");
        assertEquals(info07.toString(), "PathInfo{hasRoot=true, root='\\', fullPath='\\a\\b', parentPath='\\a', fileName=FileName{name='b', exts=[\"b\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"\", \"a\", \"b\"], separator='\\', separatorType=BACKSLASH}");
        assertEquals(info08.toString(), "PathInfo{hasRoot=false, root=null, fullPath='.\\a\\b\\c', parentPath='.\\a\\b', fileName=FileName{name='c', exts=[\"c\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\".\", \"a\", \"b\", \"c\"], separator='\\', separatorType=BACKSLASH}");
        assertEquals(info09.toString(), "PathInfo{hasRoot=false, root=null, fullPath='.\\a\\b\\c', parentPath='.\\a\\b', fileName=FileName{name='c', exts=[\"c\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\".\", \"a\", \"b\", \"c\"], separator='\\', separatorType=BACKSLASH}");
        assertEquals(info10.toString(), "PathInfo{hasRoot=false, root=null, fullPath='.\\a\\b\\c', parentPath='.\\a\\b', fileName=FileName{name='c', exts=[\"c\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\".\", \"a\", \"b\", \"c\"], separator='\\', separatorType=BACKSLASH}");
        assertEquals(info11.toString(), "PathInfo{hasRoot=false, root=null, fullPath='.\\a\\111.abc.txt', parentPath='.\\a', fileName=FileName{name='111.abc.txt', exts=[\"111\", \"abc\", \"txt\"], nameNoExt='111.abc', nameNoExt1='111', nameNoExt2=null, ext='.txt', ext1='.abc.txt', ext2=null, extNoDot='txt', extNoDot1='abc.txt', extNoDot2=null}, paths=[\".\", \"a\", \"111.abc.txt\"], separator='\\', separatorType=BACKSLASH}");
        assertEquals(info12.toString(), "PathInfo{hasRoot=false, root=null, fullPath='.\\a\\111.abc.tx\\t', parentPath='.\\a\\111.abc.tx', fileName=FileName{name='t', exts=[\"t\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\".\", \"a\", \"111.abc.tx\", \"t\"], separator='\\', separatorType=BACKSLASH}");
        assertEquals(info13.toString(), "PathInfo{hasRoot=false, root=null, fullPath='.\\a\\111.abc.tx\\t', parentPath='.\\a\\111.abc.tx', fileName=FileName{name='t', exts=[\"t\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\".\", \"a\", \"111.abc.tx\", \"t\"], separator='\\', separatorType=BACKSLASH}");
        assertEquals(info14.toString(), "PathInfo{hasRoot=false, root=null, fullPath='.\\a\\111.abc.txt', parentPath='.\\a', fileName=FileName{name='111.abc.txt', exts=[\"111\", \"abc\", \"txt\"], nameNoExt='111.abc', nameNoExt1='111', nameNoExt2=null, ext='.txt', ext1='.abc.txt', ext2=null, extNoDot='txt', extNoDot1='abc.txt', extNoDot2=null}, paths=[\".\", \"a\", \"111.abc.txt\"], separator='\\', separatorType=BACKSLASH}");
        assertEquals(info15.toString(), "PathInfo{hasRoot=false, root=null, fullPath='.\\a\\b\\c', parentPath='.\\a\\b', fileName=FileName{name='c', exts=[\"c\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\".\", \"a\", \"b\", \"c\"], separator='\\', separatorType=BACKSLASH}");
        assertEquals(info16.toString(), "PathInfo{hasRoot=false, root=null, fullPath='.\\a\\b\\c\\..', parentPath='.\\a\\b\\c', fileName=FileName{name='..', exts=[], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\".\", \"a\", \"b\", \"c\", \"..\"], separator='\\', separatorType=BACKSLASH}");
        assertEquals(info17.toString(), "PathInfo{hasRoot=false, root=null, fullPath='.\\a\\b\\c\\..', parentPath='.\\a\\b\\c', fileName=FileName{name='..', exts=[], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\".\", \"a\", \"b\", \"c\", \"..\"], separator='\\', separatorType=BACKSLASH}");
        assertEquals(info18.toString(), "PathInfo{hasRoot=false, root=null, fullPath='.\\a\\b\\c\\..', parentPath='.\\a\\b\\c', fileName=FileName{name='..', exts=[], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\".\", \"a\", \"b\", \"c\", \"..\"], separator='\\', separatorType=BACKSLASH}");
        assertEquals(info19.toString(), "PathInfo{hasRoot=false, root=null, fullPath='..', parentPath=null, fileName=FileName{name='..', exts=[], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"..\"], separator='\\', separatorType=BACKSLASH}");
        assertEquals(info20.toString(), "PathInfo{hasRoot=false, root=null, fullPath='..', parentPath=null, fileName=FileName{name='..', exts=[], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"..\"], separator='\\', separatorType=BACKSLASH}");
        assertEquals(info21.toString(), "PathInfo{hasRoot=false, root=null, fullPath='..', parentPath=null, fileName=FileName{name='..', exts=[], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"..\"], separator='\\', separatorType=BACKSLASH}");
        assertEquals(info22.toString(), "PathInfo{hasRoot=false, root=null, fullPath='......', parentPath=null, fileName=FileName{name='......', exts=[], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"......\"], separator='\\', separatorType=BACKSLASH}");
        assertEquals(info23.toString(), "PathInfo{hasRoot=false, root=null, fullPath='.... ..', parentPath=null, fileName=FileName{name='.... ..', exts=[\"\", \"\", \"\", \"\", \" \", \"\", \"\"], nameNoExt='.... .', nameNoExt1='.... ', nameNoExt2='...', ext='.', ext1='..', ext2='. ..', extNoDot='', extNoDot1='.', extNoDot2=' ..'}, paths=[\".... ..\"], separator='\\', separatorType=BACKSLASH}");
        assertEquals(info24.toString(), "PathInfo{hasRoot=false, root=null, fullPath='.\\abc.', parentPath='.', fileName=FileName{name='abc.', exts=[\"abc\", \"\"], nameNoExt='abc', nameNoExt1=null, nameNoExt2=null, ext='.', ext1=null, ext2=null, extNoDot='', extNoDot1=null, extNoDot2=null}, paths=[\".\", \"abc.\"], separator='\\', separatorType=BACKSLASH}");
        assertEquals(info25.toString(), "PathInfo{hasRoot=false, root=null, fullPath='.\\abc...', parentPath='.', fileName=FileName{name='abc...', exts=[\"abc\", \"\", \"\", \"\"], nameNoExt='abc..', nameNoExt1='abc.', nameNoExt2='abc', ext='.', ext1='..', ext2='...', extNoDot='', extNoDot1='.', extNoDot2='..'}, paths=[\".\", \"abc...\"], separator='\\', separatorType=BACKSLASH}");
        assertEquals(info26.toString(), "PathInfo{hasRoot=false, root=null, fullPath='.\\abc.tar.gz', parentPath='.', fileName=FileName{name='abc.tar.gz', exts=[\"abc\", \"tar\", \"gz\"], nameNoExt='abc.tar', nameNoExt1='abc', nameNoExt2=null, ext='.gz', ext1='.tar.gz', ext2=null, extNoDot='gz', extNoDot1='tar.gz', extNoDot2=null}, paths=[\".\", \"abc.tar.gz\"], separator='\\', separatorType=BACKSLASH}");
        assertEquals(info27.toString(), "PathInfo{hasRoot=true, root='C:\\', fullPath='C:', parentPath=null, fileName=FileName{name=null, exts=null, nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"C:\"], separator='\\', separatorType=BACKSLASH}");
        assertEquals(info28.toString(), "PathInfo{hasRoot=true, root='d:\\', fullPath='d:', parentPath=null, fileName=FileName{name=null, exts=null, nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"d:\"], separator='\\', separatorType=BACKSLASH}");
        assertEquals(info29.toString(), "PathInfo{hasRoot=true, root='d:\\', fullPath='d:', parentPath=null, fileName=FileName{name=null, exts=null, nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"d:\"], separator='\\', separatorType=BACKSLASH}");
        assertEquals(info30.toString(), "PathInfo{hasRoot=true, root='d:\\', fullPath='d:\\a', parentPath='d:', fileName=FileName{name='a', exts=[\"a\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"d:\", \"a\"], separator='\\', separatorType=BACKSLASH}");
        assertEquals(info31.toString(), "PathInfo{hasRoot=true, root='d:\\', fullPath='d:\\a', parentPath='d:', fileName=FileName{name='a', exts=[\"a\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"d:\", \"a\"], separator='\\', separatorType=BACKSLASH}");
        assertEquals(info32.toString(), "PathInfo{hasRoot=false, root=null, fullPath='d:a', parentPath=null, fileName=FileName{name='d:a', exts=[\"d:a\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"d:a\"], separator='\\', separatorType=BACKSLASH}");
        assertEquals(info33.toString(), "PathInfo{hasRoot=false, root=null, fullPath='d:a', parentPath=null, fileName=FileName{name='d:a', exts=[\"d:a\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"d:a\"], separator='\\', separatorType=BACKSLASH}");
        assertEquals(info34.toString(), "PathInfo{hasRoot=false, root=null, fullPath='d:a', parentPath=null, fileName=FileName{name='d:a', exts=[\"d:a\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"d:a\"], separator='\\', separatorType=BACKSLASH}");
        assertEquals(info35.toString(), "PathInfo{hasRoot=false, root=null, fullPath='ad:', parentPath=null, fileName=FileName{name='ad:', exts=[\"ad:\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"ad:\"], separator='\\', separatorType=BACKSLASH}");
        assertEquals(info36.toString(), "PathInfo{hasRoot=false, root=null, fullPath='ad:', parentPath=null, fileName=FileName{name='ad:', exts=[\"ad:\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"ad:\"], separator='\\', separatorType=BACKSLASH}");
        assertEquals(info37.toString(), "PathInfo{hasRoot=false, root=null, fullPath='ad:', parentPath=null, fileName=FileName{name='ad:', exts=[\"ad:\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"ad:\"], separator='\\', separatorType=BACKSLASH}");
        assertEquals(info38.toString(), "PathInfo{hasRoot=true, root='\\', fullPath='\\d:', parentPath='\\', fileName=FileName{name='d:', exts=[\"d:\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"\", \"d:\"], separator='\\', separatorType=BACKSLASH}");
        assertEquals(info39.toString(), "PathInfo{hasRoot=true, root='\\', fullPath='\\d:', parentPath='\\', fileName=FileName{name='d:', exts=[\"d:\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"\", \"d:\"], separator='\\', separatorType=BACKSLASH}");
        assertEquals(info40.toString(), "PathInfo{hasRoot=true, root='\\', fullPath='\\d:', parentPath='\\', fileName=FileName{name='d:', exts=[\"d:\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"\", \"d:\"], separator='\\', separatorType=BACKSLASH}");
        assertEquals(info41.toString(), "PathInfo{hasRoot=true, root='\\', fullPath='\\d:\\a', parentPath='\\d:', fileName=FileName{name='a', exts=[\"a\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"\", \"d:\", \"a\"], separator='\\', separatorType=BACKSLASH}");
        assertEquals(info42.toString(), "PathInfo{hasRoot=true, root='\\', fullPath='\\d:', parentPath='\\', fileName=FileName{name='d:', exts=[\"d:\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"\", \"d:\"], separator='\\', separatorType=BACKSLASH}");
        assertEquals(info43.toString(), "PathInfo{hasRoot=true, root='\\', fullPath='\\d:', parentPath='\\', fileName=FileName{name='d:', exts=[\"d:\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"\", \"d:\"], separator='\\', separatorType=BACKSLASH}");
        assertEquals(info44.toString(), "PathInfo{hasRoot=true, root='\\', fullPath='\\d:', parentPath='\\', fileName=FileName{name='d:', exts=[\"d:\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"\", \"d:\"], separator='\\', separatorType=BACKSLASH}");
        assertEquals(info45.toString(), "PathInfo{hasRoot=true, root='\\', fullPath='\\d:\\a', parentPath='\\d:', fileName=FileName{name='a', exts=[\"a\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"\", \"d:\", \"a\"], separator='\\', separatorType=BACKSLASH}");

    }

    @Test
    public void testPathInfoSlash() {
        PathInfo info01 = FilePath.infoSlash("");
        PathInfo info02 = FilePath.infoSlash("/");
        PathInfo info03 = FilePath.infoSlash("\\");
        PathInfo info04 = FilePath.infoSlash(".");
        PathInfo info05 = FilePath.infoSlash("/\\");
        PathInfo info06 = FilePath.infoSlash("///a");
        PathInfo info07 = FilePath.infoSlash("///a/b/");
        PathInfo info08 = FilePath.infoSlash("./a/b\\c\\");
        PathInfo info09 = FilePath.infoSlash(".///a\\b//\\c");
        PathInfo info10 = FilePath.infoSlash(".///a\\b//\\c/");
        PathInfo info11 = FilePath.infoSlash(".///a/111.abc.txt");
        PathInfo info12 = FilePath.infoSlash(".///a/111.abc.tx\\t");
        PathInfo info13 = FilePath.infoSlash(".///a/111.abc.tx/t");
        PathInfo info14 = FilePath.infoSlash(".///a/111.abc.txt/");
        PathInfo info15 = FilePath.infoSlash(".///a\\b//\\c/.");
        PathInfo info16 = FilePath.infoSlash(".///a\\b//\\c/..");
        PathInfo info17 = FilePath.infoSlash(".///a\\b//\\c/..\\");
        PathInfo info18 = FilePath.infoSlash(".///a\\b//\\c/../");
        PathInfo info19 = FilePath.infoSlash("..");
        PathInfo info20 = FilePath.infoSlash("..\\");
        PathInfo info21 = FilePath.infoSlash("../");
        PathInfo info22 = FilePath.infoSlash("......");
        PathInfo info23 = FilePath.infoSlash(".... ..");
        PathInfo info24 = FilePath.infoSlash("./abc.");
        PathInfo info25 = FilePath.infoSlash("./abc...");
        PathInfo info26 = FilePath.infoSlash("./abc.tar.gz");
        PathInfo info27 = FilePath.infoSlash("C:");
        PathInfo info28 = FilePath.infoSlash("d:/");
        PathInfo info29 = FilePath.infoSlash("d:\\");
        PathInfo info30 = FilePath.infoSlash("d:/a");
        PathInfo info31 = FilePath.infoSlash("d:\\a");
        PathInfo info32 = FilePath.infoSlash("d:a");
        PathInfo info33 = FilePath.infoSlash("d:a/");
        PathInfo info34 = FilePath.infoSlash("d:a\\");
        PathInfo info35 = FilePath.infoSlash("ad:");
        PathInfo info36 = FilePath.infoSlash("ad:/");
        PathInfo info37 = FilePath.infoSlash("ad:\\");
        PathInfo info38 = FilePath.infoSlash("/d:");
        PathInfo info39 = FilePath.infoSlash("/d:/");
        PathInfo info40 = FilePath.infoSlash("/d:\\");
        PathInfo info41 = FilePath.infoSlash("/d:/a");
        PathInfo info42 = FilePath.infoSlash("\\d:");
        PathInfo info43 = FilePath.infoSlash("\\d:/");
        PathInfo info44 = FilePath.infoSlash("\\d:\\");
        PathInfo info45 = FilePath.infoSlash("\\d:/a");

        // System.out.println("info01: " + info01);
        // System.out.println("info02: " + info02);
        // System.out.println("info03: " + info03);
        // System.out.println("info04: " + info04);
        // System.out.println("info05: " + info05);
        // System.out.println("info06: " + info06);
        // System.out.println("info07: " + info07);
        // System.out.println("info08: " + info08);
        // System.out.println("info09: " + info09);
        // System.out.println("info10: " + info10);
        // System.out.println("info11: " + info11);
        // System.out.println("info12: " + info12);
        // System.out.println("info13: " + info13);
        // System.out.println("info14: " + info14);
        // System.out.println("info15: " + info15);
        // System.out.println("info16: " + info16);
        // System.out.println("info17: " + info17);
        // System.out.println("info18: " + info18);
        // System.out.println("info19: " + info19);
        // System.out.println("info20: " + info20);
        // System.out.println("info21: " + info21);
        // System.out.println("info22: " + info22);
        // System.out.println("info23: " + info23);
        // System.out.println("info24: " + info24);
        // System.out.println("info25: " + info25);
        // System.out.println("info26: " + info26);
        // System.out.println("info27: " + info27);
        // System.out.println("info28: " + info28);
        // System.out.println("info29: " + info29);
        // System.out.println("info30: " + info30);
        // System.out.println("info31: " + info31);
        // System.out.println("info32: " + info32);
        // System.out.println("info33: " + info33);
        // System.out.println("info34: " + info34);
        // System.out.println("info35: " + info35);
        // System.out.println("info36: " + info36);
        // System.out.println("info37: " + info37);
        // System.out.println("info38: " + info38);
        // System.out.println("info39: " + info39);
        // System.out.println("info40: " + info40);
        // System.out.println("info41: " + info41);
        // System.out.println("info42: " + info42);
        // System.out.println("info43: " + info43);
        // System.out.println("info44: " + info44);
        // System.out.println("info45: " + info45);

        assertNull(info01);
        assertEquals(info02.toString(), "PathInfo{hasRoot=true, root='/', fullPath='/', parentPath=null, fileName=FileName{name=null, exts=null, nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[], separator='/', separatorType=WIN_SLASH}");
        assertEquals(info03.toString(), "PathInfo{hasRoot=true, root='/', fullPath='/', parentPath=null, fileName=FileName{name=null, exts=null, nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[], separator='/', separatorType=WIN_SLASH}");
        assertEquals(info04.toString(), "PathInfo{hasRoot=false, root=null, fullPath='.', parentPath=null, fileName=FileName{name='.', exts=[], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\".\"], separator='/', separatorType=WIN_SLASH}");
        assertEquals(info05.toString(), "PathInfo{hasRoot=true, root='/', fullPath='/', parentPath=null, fileName=FileName{name=null, exts=null, nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[], separator='/', separatorType=WIN_SLASH}");
        assertEquals(info06.toString(), "PathInfo{hasRoot=true, root='/', fullPath='/a', parentPath='/', fileName=FileName{name='a', exts=[\"a\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"\", \"a\"], separator='/', separatorType=WIN_SLASH}");
        assertEquals(info07.toString(), "PathInfo{hasRoot=true, root='/', fullPath='/a/b', parentPath='/a', fileName=FileName{name='b', exts=[\"b\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"\", \"a\", \"b\"], separator='/', separatorType=WIN_SLASH}");
        assertEquals(info08.toString(), "PathInfo{hasRoot=false, root=null, fullPath='./a/b/c', parentPath='./a/b', fileName=FileName{name='c', exts=[\"c\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\".\", \"a\", \"b\", \"c\"], separator='/', separatorType=WIN_SLASH}");
        assertEquals(info09.toString(), "PathInfo{hasRoot=false, root=null, fullPath='./a/b/c', parentPath='./a/b', fileName=FileName{name='c', exts=[\"c\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\".\", \"a\", \"b\", \"c\"], separator='/', separatorType=WIN_SLASH}");
        assertEquals(info10.toString(), "PathInfo{hasRoot=false, root=null, fullPath='./a/b/c', parentPath='./a/b', fileName=FileName{name='c', exts=[\"c\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\".\", \"a\", \"b\", \"c\"], separator='/', separatorType=WIN_SLASH}");
        assertEquals(info11.toString(), "PathInfo{hasRoot=false, root=null, fullPath='./a/111.abc.txt', parentPath='./a', fileName=FileName{name='111.abc.txt', exts=[\"111\", \"abc\", \"txt\"], nameNoExt='111.abc', nameNoExt1='111', nameNoExt2=null, ext='.txt', ext1='.abc.txt', ext2=null, extNoDot='txt', extNoDot1='abc.txt', extNoDot2=null}, paths=[\".\", \"a\", \"111.abc.txt\"], separator='/', separatorType=WIN_SLASH}");
        assertEquals(info12.toString(), "PathInfo{hasRoot=false, root=null, fullPath='./a/111.abc.tx/t', parentPath='./a/111.abc.tx', fileName=FileName{name='t', exts=[\"t\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\".\", \"a\", \"111.abc.tx\", \"t\"], separator='/', separatorType=WIN_SLASH}");
        assertEquals(info13.toString(), "PathInfo{hasRoot=false, root=null, fullPath='./a/111.abc.tx/t', parentPath='./a/111.abc.tx', fileName=FileName{name='t', exts=[\"t\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\".\", \"a\", \"111.abc.tx\", \"t\"], separator='/', separatorType=WIN_SLASH}");
        assertEquals(info14.toString(), "PathInfo{hasRoot=false, root=null, fullPath='./a/111.abc.txt', parentPath='./a', fileName=FileName{name='111.abc.txt', exts=[\"111\", \"abc\", \"txt\"], nameNoExt='111.abc', nameNoExt1='111', nameNoExt2=null, ext='.txt', ext1='.abc.txt', ext2=null, extNoDot='txt', extNoDot1='abc.txt', extNoDot2=null}, paths=[\".\", \"a\", \"111.abc.txt\"], separator='/', separatorType=WIN_SLASH}");
        assertEquals(info15.toString(), "PathInfo{hasRoot=false, root=null, fullPath='./a/b/c', parentPath='./a/b', fileName=FileName{name='c', exts=[\"c\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\".\", \"a\", \"b\", \"c\"], separator='/', separatorType=WIN_SLASH}");
        assertEquals(info16.toString(), "PathInfo{hasRoot=false, root=null, fullPath='./a/b/c/..', parentPath='./a/b/c', fileName=FileName{name='..', exts=[], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\".\", \"a\", \"b\", \"c\", \"..\"], separator='/', separatorType=WIN_SLASH}");
        assertEquals(info17.toString(), "PathInfo{hasRoot=false, root=null, fullPath='./a/b/c/..', parentPath='./a/b/c', fileName=FileName{name='..', exts=[], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\".\", \"a\", \"b\", \"c\", \"..\"], separator='/', separatorType=WIN_SLASH}");
        assertEquals(info18.toString(), "PathInfo{hasRoot=false, root=null, fullPath='./a/b/c/..', parentPath='./a/b/c', fileName=FileName{name='..', exts=[], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\".\", \"a\", \"b\", \"c\", \"..\"], separator='/', separatorType=WIN_SLASH}");
        assertEquals(info19.toString(), "PathInfo{hasRoot=false, root=null, fullPath='..', parentPath=null, fileName=FileName{name='..', exts=[], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"..\"], separator='/', separatorType=WIN_SLASH}");
        assertEquals(info20.toString(), "PathInfo{hasRoot=false, root=null, fullPath='..', parentPath=null, fileName=FileName{name='..', exts=[], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"..\"], separator='/', separatorType=WIN_SLASH}");
        assertEquals(info21.toString(), "PathInfo{hasRoot=false, root=null, fullPath='..', parentPath=null, fileName=FileName{name='..', exts=[], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"..\"], separator='/', separatorType=WIN_SLASH}");
        assertEquals(info22.toString(), "PathInfo{hasRoot=false, root=null, fullPath='......', parentPath=null, fileName=FileName{name='......', exts=[], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"......\"], separator='/', separatorType=WIN_SLASH}");
        assertEquals(info23.toString(), "PathInfo{hasRoot=false, root=null, fullPath='.... ..', parentPath=null, fileName=FileName{name='.... ..', exts=[\"\", \"\", \"\", \"\", \" \", \"\", \"\"], nameNoExt='.... .', nameNoExt1='.... ', nameNoExt2='...', ext='.', ext1='..', ext2='. ..', extNoDot='', extNoDot1='.', extNoDot2=' ..'}, paths=[\".... ..\"], separator='/', separatorType=WIN_SLASH}");
        assertEquals(info24.toString(), "PathInfo{hasRoot=false, root=null, fullPath='./abc.', parentPath='.', fileName=FileName{name='abc.', exts=[\"abc\", \"\"], nameNoExt='abc', nameNoExt1=null, nameNoExt2=null, ext='.', ext1=null, ext2=null, extNoDot='', extNoDot1=null, extNoDot2=null}, paths=[\".\", \"abc.\"], separator='/', separatorType=WIN_SLASH}");
        assertEquals(info25.toString(), "PathInfo{hasRoot=false, root=null, fullPath='./abc...', parentPath='.', fileName=FileName{name='abc...', exts=[\"abc\", \"\", \"\", \"\"], nameNoExt='abc..', nameNoExt1='abc.', nameNoExt2='abc', ext='.', ext1='..', ext2='...', extNoDot='', extNoDot1='.', extNoDot2='..'}, paths=[\".\", \"abc...\"], separator='/', separatorType=WIN_SLASH}");
        assertEquals(info26.toString(), "PathInfo{hasRoot=false, root=null, fullPath='./abc.tar.gz', parentPath='.', fileName=FileName{name='abc.tar.gz', exts=[\"abc\", \"tar\", \"gz\"], nameNoExt='abc.tar', nameNoExt1='abc', nameNoExt2=null, ext='.gz', ext1='.tar.gz', ext2=null, extNoDot='gz', extNoDot1='tar.gz', extNoDot2=null}, paths=[\".\", \"abc.tar.gz\"], separator='/', separatorType=WIN_SLASH}");
        assertEquals(info27.toString(), "PathInfo{hasRoot=true, root='C:/', fullPath='C:', parentPath=null, fileName=FileName{name=null, exts=null, nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"C:\"], separator='/', separatorType=WIN_SLASH}");
        assertEquals(info28.toString(), "PathInfo{hasRoot=true, root='d:/', fullPath='d:', parentPath=null, fileName=FileName{name=null, exts=null, nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"d:\"], separator='/', separatorType=WIN_SLASH}");
        assertEquals(info29.toString(), "PathInfo{hasRoot=true, root='d:/', fullPath='d:', parentPath=null, fileName=FileName{name=null, exts=null, nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"d:\"], separator='/', separatorType=WIN_SLASH}");
        assertEquals(info30.toString(), "PathInfo{hasRoot=true, root='d:/', fullPath='d:/a', parentPath='d:', fileName=FileName{name='a', exts=[\"a\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"d:\", \"a\"], separator='/', separatorType=WIN_SLASH}");
        assertEquals(info31.toString(), "PathInfo{hasRoot=true, root='d:/', fullPath='d:/a', parentPath='d:', fileName=FileName{name='a', exts=[\"a\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"d:\", \"a\"], separator='/', separatorType=WIN_SLASH}");
        assertEquals(info32.toString(), "PathInfo{hasRoot=false, root=null, fullPath='d:a', parentPath=null, fileName=FileName{name='d:a', exts=[\"d:a\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"d:a\"], separator='/', separatorType=WIN_SLASH}");
        assertEquals(info33.toString(), "PathInfo{hasRoot=false, root=null, fullPath='d:a', parentPath=null, fileName=FileName{name='d:a', exts=[\"d:a\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"d:a\"], separator='/', separatorType=WIN_SLASH}");
        assertEquals(info34.toString(), "PathInfo{hasRoot=false, root=null, fullPath='d:a', parentPath=null, fileName=FileName{name='d:a', exts=[\"d:a\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"d:a\"], separator='/', separatorType=WIN_SLASH}");
        assertEquals(info35.toString(), "PathInfo{hasRoot=false, root=null, fullPath='ad:', parentPath=null, fileName=FileName{name='ad:', exts=[\"ad:\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"ad:\"], separator='/', separatorType=WIN_SLASH}");
        assertEquals(info36.toString(), "PathInfo{hasRoot=false, root=null, fullPath='ad:', parentPath=null, fileName=FileName{name='ad:', exts=[\"ad:\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"ad:\"], separator='/', separatorType=WIN_SLASH}");
        assertEquals(info37.toString(), "PathInfo{hasRoot=false, root=null, fullPath='ad:', parentPath=null, fileName=FileName{name='ad:', exts=[\"ad:\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"ad:\"], separator='/', separatorType=WIN_SLASH}");
        assertEquals(info38.toString(), "PathInfo{hasRoot=true, root='/', fullPath='/d:', parentPath='/', fileName=FileName{name='d:', exts=[\"d:\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"\", \"d:\"], separator='/', separatorType=WIN_SLASH}");
        assertEquals(info39.toString(), "PathInfo{hasRoot=true, root='/', fullPath='/d:', parentPath='/', fileName=FileName{name='d:', exts=[\"d:\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"\", \"d:\"], separator='/', separatorType=WIN_SLASH}");
        assertEquals(info40.toString(), "PathInfo{hasRoot=true, root='/', fullPath='/d:', parentPath='/', fileName=FileName{name='d:', exts=[\"d:\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"\", \"d:\"], separator='/', separatorType=WIN_SLASH}");
        assertEquals(info41.toString(), "PathInfo{hasRoot=true, root='/', fullPath='/d:/a', parentPath='/d:', fileName=FileName{name='a', exts=[\"a\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"\", \"d:\", \"a\"], separator='/', separatorType=WIN_SLASH}");
        assertEquals(info42.toString(), "PathInfo{hasRoot=true, root='/', fullPath='/d:', parentPath='/', fileName=FileName{name='d:', exts=[\"d:\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"\", \"d:\"], separator='/', separatorType=WIN_SLASH}");
        assertEquals(info43.toString(), "PathInfo{hasRoot=true, root='/', fullPath='/d:', parentPath='/', fileName=FileName{name='d:', exts=[\"d:\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"\", \"d:\"], separator='/', separatorType=WIN_SLASH}");
        assertEquals(info44.toString(), "PathInfo{hasRoot=true, root='/', fullPath='/d:', parentPath='/', fileName=FileName{name='d:', exts=[\"d:\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"\", \"d:\"], separator='/', separatorType=WIN_SLASH}");
        assertEquals(info45.toString(), "PathInfo{hasRoot=true, root='/', fullPath='/d:/a', parentPath='/d:', fileName=FileName{name='a', exts=[\"a\"], nameNoExt=null, nameNoExt1=null, nameNoExt2=null, ext=null, ext1=null, ext2=null, extNoDot=null, extNoDot1=null, extNoDot2=null}, paths=[\"\", \"d:\", \"a\"], separator='/', separatorType=WIN_SLASH}");

    }

}
